### ISSUE TITLE
Download Freeze

### ISSUE THREAD

**Issue by nateg2** [dannysmc95/AppStore-Website#2]
@dannysmc95 I got so excited when the new update came out 2 days ago. I downloaded it and then when downloading a program, I named it and it said saved but froze. Couldn't do anything. You could also tell when it freezes because the clock will stop on the program. Luckily the old one is still fully functional but plz fix this!
btw I think what you have done is EPIC and unbelievable

**Comment by dannysmc95** [comment]
@nateg2 thanks man, means a lot, can you post some screen shots? Also can you post it on the other repo as this is for the website :PPP It should be called AppStoreCC or just AppStore. Cheers
